import React from 'react'
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'
import Modal from '@mui/material/Modal'
import { Button } from '@material-ui/core'
import CloseIcon from '@material-ui/icons/Close'
import './ModalPostagem.css'
import { Box } from '@mui/material'
import CadastroPostagem from './ca'
